# entrypoint playbook

- name: Basic setup
  hosts: all
  tasks:
    - ansible.builtin.import_tasks: tasks/base.yml

- name: Setup PostgreSQL
  hosts: postgresql
  tasks:
    - ansible.builtin.import_tasks: tasks/postgresql.yml

- name: Setup Docker engine
  hosts: docker
  tasks:
    - ansible.builtin.import_tasks: tasks/docker.yml
