- name: Install docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true
- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    filename: docker
    state: present
  vars:
    dpkg_arch: |-
      {% if ansible_facts.architecture == "x86_64" %}
      amd64
      {% elif ansible_facts.architecture == "aarch64" %}
      arm64
      {% else %}
      {{ ansible_facts.architecture }}
      {% endif %}
  become: true
- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    groups:
      - docker
    append: true
    state: present
  become: true
- name: Reconnect
  ansible.builtin.meta: reset_connection
