- name: Install apt packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
  become: true
- name: Start PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  become: true
