- name: Setup postgres venv
  ansible.builtin.pip:
    name:
      - psycopg2-binary
    virtualenv: "{{ postgresql.venv_dir }}"
    virtualenv_command: "{{ ansible_facts.python.executable }} -m venv"
  become: true
  become_user: postgres
